# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
                ('item_price', models.FloatField()),
                ('item_status', models.BooleanField()),
                ('add_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_text', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggie.Offer'),
        ),
    ]
