# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0002_auto_20170606_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_description',
            field=models.TextField(),
        ),
    ]
