# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0006_auto_20170606_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdate',
            name='offer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veggie.Offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veggie.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggie.Order'),
        ),
    ]
