# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0007_auto_20170606_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdate',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
