# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0009_auto_20170606_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdate',
            name='available_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
