# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0010_orderdate_available_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirm_hash',
            field=models.CharField(default='bbbbbbbbbbbb', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_edit_hash',
            field=models.CharField(default='ccccccccccccc', max_length=100),
            preserve_default=False,
        ),
    ]
