# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0011_auto_20170606_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
