# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0013_auto_20170607_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_unitsize',
            field=models.CharField(default='EUR/kg', max_length=10),
        ),
    ]
