# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0015_remove_order_order_edit_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
