# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0019_auto_20170618_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
