# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0021_auto_20170619_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_date',
            field=models.DateTimeField(null=True),
        ),
    ]
