# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0022_order_cancel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_unitsize',
            field=models.CharField(default='EUR/kg', max_length=15),
        ),
    ]
